### ISSUE TITLE
Operand keystrokes 

### ISSUE THREAD

**Issue by Ivan64** [frossm/rpncalc#11]
Is it possible for operand keystrokes to include implicit enters like they do on a physical RPN calculator?

**Comment by frossm** [comment]
Hello Ivan.  That's a good idea and I'll have to look into it.  Currently the input is processed after enter is pressed.  I'm not sure if I can "watch" what's being typed in a command line based input.  I don't think that's possible, but I'll look into jLine3 (which is the library I use for command line input.)

I'll have get back to you.

Michael

**Comment by frossm** [comment]
Hello Ivan64 - There might be a way to do it be collecting input in RAW mode and processing it.  I'm not sure I can get it it work, but it might be possible.

How would you expect it to work?  My guess is that if you type one of the [Operands](https://frossm.github.io/RPNCalc-UserGuide/Chapters/Operands.html) it would automatically send `enter`.  Please let me know what you think and I'll see what I can do.

Might make sense to have this as a setting so folks can turn it on/off.

Good idea by the way.

Michael

**Comment by frossm** [comment]
Hello Ivan - I've been looking into this, and it's not working very well.  It just doesn't work cleanly in a console based application.  I like the idea, but I'm going to set the investigation aside and close this for the time being.

Thank you very much for your suggestion.
