### ISSUE TITLE
support max min sum ...

### ISSUE THREAD

**Issue by jobmission** [frossm/rpncalc#3]
Great project!

Support max min sum and user-defined operation keywords .

**Comment by frossm** [comment]
Hello @jobmission 

I've just uploaded the ability to record user functions, and play them back.  Check out the READM.md and let me know if you have any questions.  The snaps are building now and I'm going to leave them in EDGE for a few days before I promote it to stable.  If you 'd like to take a look, remove your current snap and install the EDGE version with the `--edge` switch.

If all this goes well, I'll be able to make future enhancements.
