### ISSUE TITLE
arrow key functioning problems

### ISSUE THREAD

**Issue by r0bis** [frossm/rpncalc#6]
How to deal with arrow keys putting garbage on screen, please? It should be something simple, I just don't know what it is. Maybe I should write a bash script to pass some options?

I currently start it with simple `java -jar rpncalc.jar`

The reason why keys are useful:
- a possibility to correct current entry by lef / right arrow keys
- perhaps a command history, that would respond to up / down arrows

At the moment it is impossible, there is only garbage in response to arrow keys. 
I am using 4.5.4 jar file from sourceforge as per instructions

Arch linux (manjaro), bash, gnome shell.

Many thanks

**Comment by frossm** [comment]
Hello r0bis, thanks for using RPNCalc - I hope you find it useful.

I primarily use windows and the arrow keys work as expected.  Up and down will move you through a history of your entries, and left / right moves you on the command line.

I just checked my Ubuntu server (v20.04) and I see "garbage" as well.  These are probably control codes that are not being interrupted correctly by the JVM.

This behavior is nothing I developed.  I use the the standard java.util.Scanner class to get the user input.  I'll have to see if I can find away to work around this issue. 

Michael

**Comment by r0bis** [comment]
`rpncalc` is very useful, indeed. But arrow key behaviour on terminal - it could be something to do with how they are interpreted.

https://stackoverflow.com/questions/21384040/why-does-the-terminal-show-a-b-c-d-when-pressing-the-arrow-k
https://stackoverflow.com/questions/4130048/recognizing-arrow-keys-with-stdin 

The links explain this a little bit, but as a non=programmer this is a bit above my understanding. But it looks like the response to the keys needs to be programmed into rpncalc for linux as it seems for now it simply returns the codes from pressing arrow keys. Other special keys like Esc do the same.

**Comment by frossm** [comment]
Thanks for the links.  I think it's a limitation of Java's scanner library.  There are other libraries.  I'll take a look today and see if I can find out that works.  JLine3 looks promising.

**Comment by frossm** [comment]
Hello r0bis.  I think I have a working version.  It will need a bunch of testing before I release it however.  If you'd like to help me test, send me an email at `rpncalc at fross dot org` and I'll email you out a test jar file.  You just have to let me know if it works for you as I can only test on Ubuntu.

Thanks!

Michael

**Comment by frossm** [comment]
Fixed as of v4.6.5

**Comment by r0bis** [comment]
Great, thanks, and you have managed to get down the size of the jar again :)
