### ISSUE TITLE
Arrow Key Usage in SNAP Installation

### ISSUE THREAD

**Issue by frossm** [frossm/rpncalc#7]
The arrow keys can be used to cycle up and down in your input history.  However, it seems to not work in a SNAP installation.  Instead of cycling, you get the up and down arrow scan codes.

I initial thought this was due to the snap wrapper that was automatically created using `/bin/sh` which wouldn't handle them correctly, but after creating my own wrapper with bash, the same behavior was observed.  

This will take more investigation and may be something I can't fix.  Here is a screen shot showing two up arrows and two down arrow presses.

![Screenshot 2022-08-20 090512](https://user-images.githubusercontent.com/1618511/185750013-ba3590bc-69a7-487c-a356-6787372baf4e.jpg)

**Comment by gnodet** [comment]
@frossm Can you paste the content of your wrapper so that I can have a look ?
I'm on OSX and `snap` does not seem to be supported, so a thin wrapper would help ;-)

**Comment by frossm** [comment]
Oh, I'm sorry if that came out.  It's not what I intended.  This seems like it's probably a windows problem.

I compile jline3 with v3.21.0 and everything is fine.  After running rpncalc and exiting, my console's tab will complete files & directories and the up arrow, for example, will show the last command.  Standard stuff.

After running with v3.22.0, when I leave my rpncalc application, the tab/arrows no longer work correctly.  I get "scan codes" (or whatever those are called).  It's like the console somehow gets screwed up.  Opening another console works correctly.
